import Foundation

/// TURN/STUN configuration.
/// Credentials are compiled in from TURNSecrets (generated by pre-build script from TURNConfig.plist).
enum TURNConfig {

    // MARK: - STUN (public, no auth required)

    static let stunURLs: [String] = [
        "stun:stun.l.google.com:19302",
        "stun:stun.relay.metered.ca:80"
    ]

    // MARK: - TURN

    static let turnURLs: [String] = [
        "turn:global.relay.metered.ca:80",
        "turn:global.relay.metered.ca:80?transport=tcp",
        "turn:global.relay.metered.ca:443",
        "turns:global.relay.metered.ca:443?transport=tcp"
    ]

    static var turnUsername: String { TURNSecrets.turnUsername }
    static var turnCredential: String { TURNSecrets.turnCredential }
    static var meteredAPIKey: String { TURNSecrets.meteredAPIKey }
}
